pipeline {
    agent any
    environment {
        DOCKER_TAG = getDockerTag()
    }

    stages {
        stage("Build Docker Image") {
            steps {
                // Push image to dockerhub
                sh "docker build -t julesc00/nodeapp:${DOCKER_TAG}"
            }
        }
    }
}

def getDockerTag() {
    // Get lastest commit code and use it for versioning.
    def tag = sh script: "git rev-parse HEAD", returnStdout: true
    return tag
}